// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/dtroode/gophkeeper-server/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// SignupStore is an autogenerated mock type for the SignupStore type
type SignupStore struct {
	mock.Mock
}

// Consume provides a mock function with given fields: ctx, sessionID
func (_m *SignupStore) Consume(ctx context.Context, sessionID string) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, pendingSignup
func (_m *SignupStore) Create(ctx context.Context, pendingSignup model.PendingSignup) error {
	ret := _m.Called(ctx, pendingSignup)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PendingSignup) error); ok {
		r0 = rf(ctx, pendingSignup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBySessionID provides a mock function with given fields: ctx, sessionID
func (_m *SignupStore) GetBySessionID(ctx context.Context, sessionID string) (model.PendingSignup, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetBySessionID")
	}

	var r0 model.PendingSignup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.PendingSignup, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.PendingSignup); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Get(0).(model.PendingSignup)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSignupStore creates a new instance of SignupStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSignupStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *SignupStore {
	mock := &SignupStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
