// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	model "github.com/dtroode/gophkeeper-server/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// StreamWriter is an autogenerated mock type for the StreamWriter type
type StreamWriter struct {
	mock.Mock
}

// Send provides a mock function with given fields: _a0
func (_m *StreamWriter) Send(_a0 *model.GetRecordStreamResponse) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.GetRecordStreamResponse) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStreamWriter creates a new instance of StreamWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStreamWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *StreamWriter {
	mock := &StreamWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
